# Generated by Django 4.1.3 on 2022-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('photo', models.ImageField(upload_to='')),
                ('role', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=200)),
                ('course', models.IntegerField(max_length=1)),
                ('inf_about', models.TextField()),
            ],
        ),
    ]
