# Generated by Django 4.1.3 on 2022-11-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_alter_team_member_color_alter_team_member_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='secret_role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team_member',
            name='tg_name',
            field=models.CharField(default='aboba', max_length=100),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='course',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
