# Generated by Django 4.1.3 on 2022-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_team_member_secret_role_team_member_tg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('blue', 'BLUE'), ('green', 'GREEN'), ('default', 'DEFAULT')], default='default', max_length=20),
        ),
    ]
