# Generated by Django 4.1.3 on 2022-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_alter_team_member_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='images/'),
        ),
    ]
