# Generated by Django 4.1.3 on 2022-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_alter_team_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='role',
            field=models.CharField(blank=True, default='зритель', max_length=100, null=True),
        ),
    ]
